export const goals = [
    {
        task: 'Levothyroxine',
        interval: 'daily',
        targetPerDuration: 1,
        achieved: 0,
        category: 'Health',
    },
    {
        task: 'Water',
        interval: 'daily',
        targetPerDuration: 2,
        achieved: 0,
        category: 'Health',
    },
    {
        task: 'Brush Teeth',
        interval: 'daily',
        targetPerDuration: 2,
        achieved: 0,
        category: 'Health',
    },
    {
        task: 'Floss',
        interval: 'daily',
        targetPerDuration: 2,
        achieved: 0,
        category: 'Health',
    },
    {
        task: 'Face Lotion',
        interval: 'daily',
        targetPerDuration: 2,
        achieved: 0,
        category: 'Health',
    },
    {
        task: 'Breakfast',
        interval: 'daily',
        targetPerDuration: 1,
        achieved: 0,
        category: 'Meals',
    },
    {
        task: 'Lunch',
        interval: 'daily',
        targetPerDuration: 1,
        achieved: 0,
        category: 'Meals',
    },
    {
        task: 'Dinner',
        interval: 'daily',
        targetPerDuration: 1,
        achieved: 0,
        category: 'Meals',
    },
    {
        task: 'Sustain Protein Shake',
        interval: 'daily',
        targetPerDuration: 2,
        achieved: 0,
        category: 'Meals',
    },
    {
        task: 'Iso Protein Shake',
        interval: 'daily',
        targetPerDuration: 1,
        achieved: 0,
        category: 'Meals',
    },
    {
        task: 'Programming',
        interval: 'daily',
        targetPerDuration: 5,
        achieved: 0,
        category: 'Education',
    },
    {
        task: 'Greek lesson',
        interval: 'daily',
        targetPerDuration: 1,
        achieved: 0,
        category: 'Education',
    },
    {
        task: 'Workout',
        interval: 'daily',
        targetPerDuration: 1,
        achieved: 0,
        category: 'Fitness',
    },
    {
        task: 'Cardio',
        interval: 'daily',
        targetPerDuration: 1,
        achieved: 0,
        category: 'Fitness',
    },
    {
        task: 'Stretch',
        interval: 'daily',
        targetPerDuration: 1,
        achieved: 0,
        category: 'Fitness',
    },

]