export const goals = [
    {
        task: 'Water',
        interval: 'daily',
        category: 'Health',
        defaultTarget: 2,
        history: [],
    },
    {
        task: 'Levothyroxine',
        interval: 'daily',
        category: 'Health',
        defaultTarget: 1,
        history: [],
    },
    {
        task: 'Brush Teeth',
        interval: 'daily',
        category: 'Health',
        defaultTarget: 2,
        history: [],
    },
    {
        task: 'Floss',
        interval: 'daily',
        category: 'Health',
        defaultTarget: 2,
        history: [],
    },
    {
        task: 'Face Lotion',
        interval: 'daily',
        category: 'Health',
        defaultTarget: 2,
        history: [],
    },
    {
        task: 'Breakfast',
        interval: 'daily',
        category: 'Meals',
        defaultTarget: 1,
        history: [],
    },
    {
        task: 'Lunch',
        interval: 'daily',
        category: 'Meals',
        defaultTarget: 1,
        history: [],
    },
    {
        task: 'Dinner',
        interval: 'daily',
        category: 'Meals',
        defaultTarget: 1,
        history: [],
    },
    {
        task: 'Sustain Protein Shake',
        interval: 'daily',
        category: 'Meals',
        defaultTarget: 2,
        history: [],
    },
    {
        task: 'Iso Protein Shake',
        interval: 'daily',
        category: 'Meals',
        defaultTarget: 1,
        history: [],
    },
    {
        task: 'Programming',
        interval: 'daily',
        category: 'Education',
        defaultTarget: 5,
        history: [],
    },
    {
        task: 'Greek lesson',
        interval: 'daily',
        category: 'Education',
        defaultTarget: 1,
        history: [],
    },
    {
        task: 'Workout',
        interval: 'daily',
        category: 'Fitness',
        defaultTarget: 1,
        history: [],
    },
    {
        task: 'Cardio',
        interval: 'daily',
        category: 'Fitness',
        defaultTarget: 1,
        history: [],
    },
    {
        task: 'Stretch',
        interval: 'daily',
        category: 'Fitness',
        defaultTarget: 1,
        history: [],
    },

]